# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Control_Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Control_Form(object):
    def setupUi(self, Control_Form):
        Control_Form.setObjectName("Control_Form")
        Control_Form.resize(430, 480)
        self.pushButton_online_control = QtWidgets.QPushButton(Control_Form)
        self.pushButton_online_control.setGeometry(QtCore.QRect(140, 100, 160, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_online_control.setFont(font)
        self.pushButton_online_control.setObjectName("pushButton_online_control")
        self.pushButton_offline_control = QtWidgets.QPushButton(Control_Form)
        self.pushButton_offline_control.setGeometry(QtCore.QRect(140, 250, 160, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_offline_control.setFont(font)
        self.pushButton_offline_control.setObjectName("pushButton_offline_control")
        self.pushButton_control_help = QtWidgets.QPushButton(Control_Form)
        self.pushButton_control_help.setGeometry(QtCore.QRect(320, 430, 93, 28))
        self.pushButton_control_help.setObjectName("pushButton_control_help")
        self.pushButton_control_back_nagivator = QtWidgets.QPushButton(Control_Form)
        self.pushButton_control_back_nagivator.setGeometry(QtCore.QRect(20, 420, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_control_back_nagivator.setFont(font)
        self.pushButton_control_back_nagivator.setObjectName("pushButton_control_back_nagivator")

        self.retranslateUi(Control_Form)
        QtCore.QMetaObject.connectSlotsByName(Control_Form)

    def retranslateUi(self, Control_Form):
        _translate = QtCore.QCoreApplication.translate
        Control_Form.setWindowTitle(_translate("Control_Form", "Form"))
        self.pushButton_online_control.setText(_translate("Control_Form", "在线控制"))
        self.pushButton_offline_control.setText(_translate("Control_Form", "离线控制"))
        self.pushButton_control_help.setText(_translate("Control_Form", "帮助"))
        self.pushButton_control_back_nagivator.setText(_translate("Control_Form", "返回导航界面"))
