# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Filter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_filter(object):
    def setupUi(self, Dialog_filter):
        Dialog_filter.setObjectName("Dialog_filter")
        Dialog_filter.resize(554, 288)
        self.frame = QtWidgets.QFrame(Dialog_filter)
        self.frame.setGeometry(QtCore.QRect(0, 0, 541, 211))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_selfdefine_filter = QtWidgets.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton_selfdefine_filter.setFont(font)
        self.radioButton_selfdefine_filter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_selfdefine_filter.setObjectName("radioButton_selfdefine_filter")
        self.verticalLayout_3.addWidget(self.radioButton_selfdefine_filter, 0, QtCore.Qt.AlignHCenter)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_lowfrequent = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_lowfrequent.setFont(font)
        self.lineEdit_lowfrequent.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_lowfrequent.setObjectName("lineEdit_lowfrequent")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_lowfrequent)
        self.lineEdit_highfrequent = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_highfrequent.setFont(font)
        self.lineEdit_highfrequent.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_highfrequent.setObjectName("lineEdit_highfrequent")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_highfrequent)
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.pushButton_start_filter = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_start_filter.setFont(font)
        self.pushButton_start_filter.setObjectName("pushButton_start_filter")
        self.verticalLayout_4.addWidget(self.pushButton_start_filter)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_band_filter = QtWidgets.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton_band_filter.setFont(font)
        self.radioButton_band_filter.setObjectName("radioButton_band_filter")
        self.verticalLayout_2.addWidget(self.radioButton_band_filter, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_Delta_band = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_Delta_band.setFont(font)
        self.checkBox_Delta_band.setObjectName("checkBox_Delta_band")
        self.verticalLayout.addWidget(self.checkBox_Delta_band)
        self.checkBox_Theta_band = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_Theta_band.setFont(font)
        self.checkBox_Theta_band.setObjectName("checkBox_Theta_band")
        self.verticalLayout.addWidget(self.checkBox_Theta_band)
        self.checkBox_Alpha_band = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_Alpha_band.setFont(font)
        self.checkBox_Alpha_band.setObjectName("checkBox_Alpha_band")
        self.verticalLayout.addWidget(self.checkBox_Alpha_band)
        self.checkBox_Beta_band = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_Beta_band.setFont(font)
        self.checkBox_Beta_band.setObjectName("checkBox_Beta_band")
        self.verticalLayout.addWidget(self.checkBox_Beta_band)
        self.checkBox_Gamma_band = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_Gamma_band.setFont(font)
        self.checkBox_Gamma_band.setObjectName("checkBox_Gamma_band")
        self.verticalLayout.addWidget(self.checkBox_Gamma_band)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.pushButton_close = QtWidgets.QPushButton(Dialog_filter)
        self.pushButton_close.setGeometry(QtCore.QRect(10, 230, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setObjectName("pushButton_close")
        self.pushButton_help = QtWidgets.QPushButton(Dialog_filter)
        self.pushButton_help.setGeometry(QtCore.QRect(470, 260, 75, 23))
        self.pushButton_help.setObjectName("pushButton_help")

        self.retranslateUi(Dialog_filter)
        self.pushButton_close.clicked.connect(Dialog_filter.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog_filter)

    def retranslateUi(self, Dialog_filter):
        _translate = QtCore.QCoreApplication.translate
        Dialog_filter.setWindowTitle(_translate("Dialog_filter", "Dialog"))
        self.radioButton_selfdefine_filter.setText(_translate("Dialog_filter", "自定义滤波"))
        self.label.setText(_translate("Dialog_filter", "截止低频(Hz)："))
        self.lineEdit_lowfrequent.setText(_translate("Dialog_filter", "8"))
        self.lineEdit_highfrequent.setText(_translate("Dialog_filter", "30"))
        self.label_2.setText(_translate("Dialog_filter", "截止高频(Hz)："))
        self.pushButton_start_filter.setText(_translate("Dialog_filter", "开始滤波"))
        self.radioButton_band_filter.setText(_translate("Dialog_filter", "频段滤波"))
        self.checkBox_Delta_band.setText(_translate("Dialog_filter", "Delta频段"))
        self.checkBox_Theta_band.setText(_translate("Dialog_filter", "Theta频段"))
        self.checkBox_Alpha_band.setText(_translate("Dialog_filter", "Alpha频段"))
        self.checkBox_Beta_band.setText(_translate("Dialog_filter", "Beta频段"))
        self.checkBox_Gamma_band.setText(_translate("Dialog_filter", "Gamma频段"))
        self.pushButton_close.setText(_translate("Dialog_filter", "关闭"))
        self.pushButton_help.setText(_translate("Dialog_filter", "帮助"))

