# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_Form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Login_From(object):
    def setupUi(self, Login_From):
        Login_From.setObjectName("Login_From")
        Login_From.resize(680, 500)
        self.label_login = QtWidgets.QLabel(Login_From)
        self.label_login.setGeometry(QtCore.QRect(120, 60, 430, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_login.setFont(font)
        self.label_login.setAlignment(QtCore.Qt.AlignCenter)
        self.label_login.setObjectName("label_login")
        self.layoutWidget = QtWidgets.QWidget(Login_From)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 170, 434, 198))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.pushButton_quit = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.gridLayout.addWidget(self.pushButton_quit, 3, 1, 1, 1)
        self.pushButton_login = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setObjectName("pushButton_login")
        self.gridLayout.addWidget(self.pushButton_login, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_name = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_name)
        self.label_password = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_password)
        self.lineEdit_name = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setInputMask("")
        self.lineEdit_name.setText("")
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_name)
        self.lineEdit_password = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setToolTipDuration(-6)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_password)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        self.pushButton_help = QtWidgets.QPushButton(Login_From)
        self.pushButton_help.setGeometry(QtCore.QRect(570, 460, 100, 30))
        self.pushButton_help.setObjectName("pushButton_help")

        self.retranslateUi(Login_From)
        self.pushButton_quit.clicked.connect(Login_From.close)
        QtCore.QMetaObject.connectSlotsByName(Login_From)

    def retranslateUi(self, Login_From):
        _translate = QtCore.QCoreApplication.translate
        Login_From.setWindowTitle(_translate("Login_From", "Form"))
        self.label_login.setText(_translate("Login_From", "Mate-BCI登录界面"))
        self.pushButton_quit.setText(_translate("Login_From", "退出"))
        self.pushButton_login.setText(_translate("Login_From", "登录"))
        self.label_name.setText(_translate("Login_From", "账号："))
        self.label_password.setText(_translate("Login_From", "密码："))
        self.lineEdit_name.setPlaceholderText(_translate("Login_From", "username"))
        self.lineEdit_password.setPlaceholderText(_translate("Login_From", "password"))
        self.pushButton_help.setText(_translate("Login_From", "帮助"))

