# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BrainGraphMonitor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from .FigureCanvas import MyFigure
class Ui_brainGraph_Form(object):
    def setupUi(self, brainGraph_Form):
        brainGraph_Form.setObjectName("brainGraph_Form")
        brainGraph_Form.resize(1235, 870)
        self.gridLayout_2 = QtWidgets.QGridLayout(brainGraph_Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_2 = QtWidgets.QWidget(brainGraph_Form)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_start = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_start.setMinimumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout.addWidget(self.pushButton_start, 1, 2, 1, 1)
        self.textEdit_order = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit_order.setMinimumSize(QtCore.QSize(1191, 101))
        self.textEdit_order.setObjectName("textEdit_order")
        self.gridLayout.addWidget(self.textEdit_order, 2, 0, 1, 4)
        self.pushButton_close = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_close.setMinimumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout.addWidget(self.pushButton_close, 1, 3, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setMinimumSize(QtCore.QSize(181, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_acquire_device = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_acquire_device.setMinimumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comboBox_acquire_device.setFont(font)
        self.comboBox_acquire_device.setObjectName("comboBox_acquire_device")
        self.comboBox_acquire_device.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_acquire_device)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_braingraph = QtWidgets.QLabel(self.widget_2)
        self.label_braingraph.setMinimumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_braingraph.setFont(font)
        self.label_braingraph.setObjectName("label_braingraph")
        self.horizontalLayout_2.addWidget(self.label_braingraph)
        self.comboBox_braingraph = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_braingraph.setMinimumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comboBox_braingraph.setFont(font)
        self.comboBox_braingraph.setObjectName("comboBox_braingraph")
        self.comboBox_braingraph.addItem("")
        self.comboBox_braingraph.addItem("")
        self.comboBox_braingraph.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_braingraph)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.Figure_braingraph = MyFigure(self.widget_2)
        self.Figure_braingraph.setMinimumSize(QtCore.QSize(1171, 551))
        self.Figure_braingraph.setObjectName("Figure_braingraph")
        self.gridLayout.addWidget(self.Figure_braingraph, 0, 0, 1, 4)
        self.pushButton_connect = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_connect.setMinimumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_connect.setFont(font)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.gridLayout.addWidget(self.pushButton_connect, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.widget_2, 0, 0, 1, 1)

        self.retranslateUi(brainGraph_Form)
        QtCore.QMetaObject.connectSlotsByName(brainGraph_Form)

    def retranslateUi(self, brainGraph_Form):
        _translate = QtCore.QCoreApplication.translate
        brainGraph_Form.setWindowTitle(_translate("brainGraph_Form", "Form"))
        self.pushButton_start.setText(_translate("brainGraph_Form", "开始"))
        self.pushButton_close.setText(_translate("brainGraph_Form", "关闭"))
        self.label.setText(_translate("brainGraph_Form", "采集设备型号："))
        self.comboBox_acquire_device.setItemText(0, _translate("brainGraph_Form", "Neuracle_Start"))
        self.label_braingraph.setText(_translate("brainGraph_Form", "脑地形图模式："))
        self.comboBox_braingraph.setItemText(0, _translate("brainGraph_Form", "ALL"))
        self.comboBox_braingraph.setItemText(1, _translate("brainGraph_Form", "C3C4"))
        self.comboBox_braingraph.setItemText(2, _translate("brainGraph_Form", "自定义"))
        self.pushButton_connect.setText(_translate("brainGraph_Form", "连接"))

