# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'offline_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_offline_Form(object):
    def setupUi(self, offline_Form):
        offline_Form.setObjectName("offline_Form")
        offline_Form.resize(800, 650)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(offline_Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.offline_tabWidget = QtWidgets.QTabWidget(offline_Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.offline_tabWidget.setFont(font)
        self.offline_tabWidget.setObjectName("offline_tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_back = QtWidgets.QPushButton(self.tab)
        self.pushButton_back.setObjectName("pushButton_back")
        self.gridLayout.addWidget(self.pushButton_back, 2, 0, 1, 1)
        self.pushButton_help = QtWidgets.QPushButton(self.tab)
        self.pushButton_help.setObjectName("pushButton_help")
        self.gridLayout.addWidget(self.pushButton_help, 2, 1, 1, 1)
        self.textEdit_order = QtWidgets.QTextEdit(self.tab)
        self.textEdit_order.setObjectName("textEdit_order")
        self.gridLayout.addWidget(self.textEdit_order, 1, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_IP = QtWidgets.QLabel(self.tab)
        self.label_IP.setObjectName("label_IP")
        self.horizontalLayout.addWidget(self.label_IP)
        self.lineEdit_IP = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_IP.setObjectName("lineEdit_IP")
        self.horizontalLayout.addWidget(self.lineEdit_IP)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_stand = QtWidgets.QPushButton(self.tab)
        self.pushButton_stand.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_stand.setObjectName("pushButton_stand")
        self.gridLayout_2.addWidget(self.pushButton_stand, 1, 0, 1, 1)
        self.pushButton_connect = QtWidgets.QPushButton(self.tab)
        self.pushButton_connect.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.gridLayout_2.addWidget(self.pushButton_connect, 0, 0, 1, 2)
        self.pushButton_sit = QtWidgets.QPushButton(self.tab)
        self.pushButton_sit.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_sit.setObjectName("pushButton_sit")
        self.gridLayout_2.addWidget(self.pushButton_sit, 1, 1, 1, 1)
        self.pushButton_left = QtWidgets.QPushButton(self.tab)
        self.pushButton_left.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_left.setObjectName("pushButton_left")
        self.gridLayout_2.addWidget(self.pushButton_left, 2, 0, 1, 1)
        self.pushButton_right = QtWidgets.QPushButton(self.tab)
        self.pushButton_right.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_right.setObjectName("pushButton_right")
        self.gridLayout_2.addWidget(self.pushButton_right, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 2)
        self.offline_tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.offline_tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.offline_tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout_2.addWidget(self.offline_tabWidget)

        self.retranslateUi(offline_Form)
        self.offline_tabWidget.setCurrentIndex(0)
        self.pushButton_back.clicked.connect(offline_Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(offline_Form)

    def retranslateUi(self, offline_Form):
        _translate = QtCore.QCoreApplication.translate
        offline_Form.setWindowTitle(_translate("offline_Form", "Form"))
        self.pushButton_back.setText(_translate("offline_Form", "返回"))
        self.pushButton_help.setText(_translate("offline_Form", "帮助"))
        self.label_IP.setText(_translate("offline_Form", "IP连接地址："))
        self.lineEdit_IP.setText(_translate("offline_Form", "192.158.2.3"))
        self.pushButton_stand.setText(_translate("offline_Form", "站立"))
        self.pushButton_connect.setText(_translate("offline_Form", "连接"))
        self.pushButton_sit.setText(_translate("offline_Form", "坐下"))
        self.pushButton_left.setText(_translate("offline_Form", "左腿迈步"))
        self.pushButton_right.setText(_translate("offline_Form", "右腿迈步"))
        self.offline_tabWidget.setTabText(self.offline_tabWidget.indexOf(self.tab), _translate("offline_Form", "下肢外骨骼"))
        self.offline_tabWidget.setTabText(self.offline_tabWidget.indexOf(self.tab_3), _translate("offline_Form", "竞速车"))
        self.offline_tabWidget.setTabText(self.offline_tabWidget.indexOf(self.tab_4), _translate("offline_Form", "上肢外骨骼"))
